const List<String> facilitiesVenue = [
  "Parking",
  "Catering",
  "Stage",
  "Decoration",
  "Air Conditioning",
  "Conference",
  "WiFi",
  "Sound System",
  "Projector",
  "Lighting",
  "Security",
  "Changing Rooms",
  "Restrooms",
  "Outdoor Space",
  "Smoking Area",
  "VIP Lounge",
  "First Aid",
  "Bar Counter",
  "Dance Floor",
  "Pool Access",
  "Gym Access",
  "Play Area for Kids",
  "Valet Parking",
  "Power Backup",
  "AV Equipment",
  "Podium",
  "Table and Chair Setup",
  "Photo Booth",
  "Green Rooms",
  "Special Effects",
  "Private Entry",
  "On-site Technician",
  "Cleaning Services",
  "Heating System",
  "Kitchen Access",
  "Pet-Friendly Facility",
  "Wheelchair Access",
  "Eco-Friendly Setup",
  "Dedicated Staff",
  "Live Streaming Support",
  "Flexible Seating Arrangements",
  "On-site Accommodation",
  "Event Insurance",
  "Fireworks Display Zone",
  "Custom Decorations",
  "Cloak Room",
  "Shuttle Service",
  "Photography/Video Services",
  "Live Entertainment Support",
  "Rehearsal Space",
  "Beverage Services",
  "Food Counters",
  "Self-Service Counters"
];
const List<String> facilitiesVehicle = [
  // General Vehicle Facilities (Applicable to all types)
  "Air Conditioning",
  "Bluetooth Connectivity",
  "GPS Navigation",
  "Music System",
  "Automatic Transmission",
  "Power Windows",
  "Cruise Control",
  "Backup Camera",
  "Parking Sensors/Camera",
  "Heated Seats",
  "Keyless Entry",
  "Tire Pressure Monitoring System (TPMS)",
  "Wireless Charging Pad",
  "Remote Start",
  "Security System",
  "Lane Assist",

  // Car Specific Facilities
  "Leather Seats",
  "Sunroof",
  "Alloy Wheels",
  "Tow Hook",
  "Bluetooth Audio Streaming",
  "Driver Assistance Systems",
  "Tinted Windows",

  // Bus Specific Facilities
  "Wheelchair Accessibility",
  "Onboard Wi-Fi",
  "Passenger Seats",
  "Air Suspension",
  "Restroom Facility",
  "Bus Wi-Fi",
  "Driver Console",
  "Overhead Luggage Storage",
  "Public Address System (PA)",

  // EV Specific Facilities
  "Electric Charging Port",
  "Regenerative Braking",
  "Battery Health Monitoring",
  "Electric Motor",
  "Eco Mode",
  "Low Emissions",
  "Green Certification",
  "Fast Charging",
  "Solar Roof",
  "EV Range Indicator",

  // Hybrid Vehicle Specific Facilities
  "Hybrid Engine",
  "Electric-Only Mode",
  "Fuel Efficiency Mode",
  "Battery Level Indicator",
  "Automatic Switching Between Power Sources",
  "Hybrid Drive",
  "Low Emissions Mode",
  "Plug-In Hybrid Capability",
  "Energy Regeneration",
];
const List<String> facilitiesDecorationStyle = [
  "Traditional",
  "Modern",
  "Rustic",
  "Bohemian",
  "Vintage",
  "Glamorous",
  "Minimalistic",
  "Classic",
  "Cultural",
  "Themed"
];
const List<String> facilitiesDecorationCategory = [
  "Stage Decoration",
  "Floral Arrangements",
  "Lighting",
  "Table Centerpieces",
  "Ceiling Decorations",
  "Backdrop Designs",
  "Mandap Decorations",
  "Entrance Arch",
  "Aisle Decorations",
  "Seating Decorations",
  "Wall Hangings",
  "Balloon Arrangements",
  "Thematic Props",
  "Car Decorations",
  "Customized Decorations",
];
