// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkayjDnGm4GVD1Fq2XDYUSwmNSsNbkqyw',
    appId: '1:269014125948:web:3214142671c6341e83e8f9',
    messagingSenderId: '269014125948',
    projectId: 'servemate-d4cef',
    authDomain: 'servemate-d4cef.firebaseapp.com',
    storageBucket: 'servemate-d4cef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsFXOhw7YflwsCWvA8emP5sFKb4E8N7E4',
    appId: '1:269014125948:ios:440cdebccc5536b083e8f9',
    messagingSenderId: '269014125948',
    projectId: 'servemate-d4cef',
    storageBucket: 'servemate-d4cef.appspot.com',
    iosBundleId: 'com.example.serveMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsFXOhw7YflwsCWvA8emP5sFKb4E8N7E4',
    appId: '1:269014125948:ios:440cdebccc5536b083e8f9',
    messagingSenderId: '269014125948',
    projectId: 'servemate-d4cef',
    storageBucket: 'servemate-d4cef.appspot.com',
    iosBundleId: 'com.example.serveMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkayjDnGm4GVD1Fq2XDYUSwmNSsNbkqyw',
    appId: '1:269014125948:web:2cee938efcf88b8b83e8f9',
    messagingSenderId: '269014125948',
    projectId: 'servemate-d4cef',
    authDomain: 'servemate-d4cef.firebaseapp.com',
    storageBucket: 'servemate-d4cef.appspot.com',
  );
}
